import type { Collection, SignPrint } from './catalog'

// The bulk of the slogan catalogue. Hand-written slogans with a blank to
// personalise live in catalog.ts; these are fixed texts, grouped by collection.

export const familyLines = [
  'I’m someone’s reason to smile',
  'Be kind. I have a family.',
  'Bringing the kids home safe',
  'Precious cargo on board',
  'Future grandma. Please pass wide.',
  'My kids think I’m a superhero. Prove them right.',
  'My cat needs me alive',
  'I promised I’d be home by six',
  'Tonight is pizza night. Let me get there.',
  'Somebody’s whole world rides this bike',
  'I’m the one who reads the bedtime stories',
  'Treat me like family',
  'Ride like someone loves you. Drive like it too.',
  'Every rider has a story',
  'I have plans for the weekend',
  'Home is where I’m heading',
  'My family rides here too',
  'On my way back to the people I love',
  'Wave at me. I might be your cousin.',
  'Please return me to my family unharmed',
  'Somebody will miss me at dinner',
]

export const seriousLines = [
  'Every rider is someone',
  'Space saves lives',
  'Close passes are never OK',
  'Give me room. It’s that simple.',
  'Wait for a safe gap',
  'Overtake like it’s your child on the bike',
  'Patience is free',
  'Your horn won’t make me faster',
  'Seen me? Good. Now give me space.',
  'Respect is free',
  'I’m allowed to be here',
  'Cycling is not a crime',
  'Bikes are traffic too',
  'Don’t rush past. Pass with care.',
  'Slow down near people',
  'Space, not speed',
  'More space. Less fear.',
  'Every metre matters',
  'Kindness keeps us alive',
  'Arrive together',
  'Slow is smooth. Smooth is safe.',
  'No overtaking on blind bends',
  'Wait behind me. It’s only a moment.',
  'Look out for each other',
  'Streets are for people',
  'Safe streets for everyone',
  'My safety is not your inconvenience',
  'One mistake is too many',
  'One mistake could cost my life',
  'Your mistake. My life.',
  'One second of distraction could cost my life',
  'Check your mirror. Check it again.',
  'Turning? Check for bikes.',
  'Headlights on. Phone away.',
  'The road belongs to all of us',
  'I ride so the air is cleaner for your kids',
  'Less speed, more life',
  'I’m vulnerable. You’re not.',
  'Your car has airbags. I don’t.',
  'Metal box vs. human body. Be careful.',
  'Pass me like you’d pass a horse',
  'I ride to work, just like you drive to work',
  'Road rage never got anyone home faster',
  'Take a breath. Then overtake.',
  'Calm roads for everyone',
  'Safety is a shared job',
  'Hurry costs lives',
]

export const funnyLines = [
  'Legs of steel. Skin of paper. Please pass wide.',
  'Pedal power activated',
  'I’m not lost. I’m on a ride.',
  'Cyclist by day, snack enthusiast by night',
  'My bike is cheaper than your parking',
  'No parking fees. No regrets.',
  'I climb hills for fun. Weird, I know.',
  'Hills are just flat roads with attitude',
  'Currently burning off tonight’s dinner',
  'This is my gym and it has a view',
  'Lycra is a lifestyle',
  'Ask me about my cadence. Actually, don’t.',
  'Tan lines are my accessories',
  'Helmet hair, don’t care',
  'I’m retired. This is my job now.',
  'Running late? Not me. I’m on a bike.',
  'My commute has birds. Yours has traffic.',
  'Zero litres per 100 km',
  'Espresso in, watts out',
  'Carbon footprint: pasta',
  'Hold my handlebars',
  'Chasing sunsets, not cars',
  'I’m in no hurry. Clearly.',
  'Honk twice if you like my socks',
  'Nice car. Mine has a bell.',
  'Ding ding! That was a friendly ding.',
  'Please don’t hit me, I just got this jersey',
  'Yes, I’m wearing Lycra. No, it’s not a phase.',
  'Snack stop in 5 km',
  'Uphill is just character building',
  'Downhill is my reward',
  'I survived the hill. Be nice.',
  'Out of breath, not out of patience',
  'Slower than you, happier than you',
  'My bike doesn’t need a car wash',
  'Tyres pumped. Mood pumped.',
  'Pedals before petrol',
  'Warning: frequent snack stops',
  'I bike, therefore I am hungry',
  'Wheelie good at being careful',
  'Spokesperson for safer roads',
  'Tired legs, happy heart',
  'Not racing. Just vibing.',
  'Just here for the café stop',
  'My other hobby is also cycling',
  'Life is better at 20 km/h',
  '20 km/h of pure joy',
  'Congestion? Never heard of her.',
  'Traffic jams are for toast',
  'Beep beep is not a love language',
  'I pedal, you smile. Deal?',
  'This bike runs on good vibes',
  'Built for comfort, not for speed',
  'Sunday rider, every day of the week',
  'I came for the views, stayed for the pastries',
  'If you can read this, thanks for the space',
  'I’ll beat you to the parking spot',
  'Cheaper than therapy',
  'Overtaking me won’t make you less late',
  'Lycra: because dignity is overrated',
  'Yes, the bike was expensive. No, I won’t discuss it.',
  'Brb, cycling up a hill for no reason',
  'Hi! I’m the traffic you’re complaining about.',
  'Please pass wide. My ego is fragile.',
  'Slow on hills, fast at café stops',
  'I’m not sweating. I’m sparkling.',
]

export const signLines: [SignPrint, string][] = [
  ['space', 'Wait. Then pass wide.'],
  ['space', 'Room for a bike, please'],
  ['space', 'Overtake with space'],
  ['space', 'Wide berth, please'],
  ['space', 'Don’t squeeze past'],
  ['space', 'Space is safety'],
  ['cyclist', 'Bikes on this road'],
  ['cyclist', 'Cyclists ahead. Be patient.'],
  ['cyclist', 'Watch for bikes'],
  ['cyclist', 'Share this lane'],
  ['cyclist', 'Bike commuter at work'],
  ['heart', 'Fragile. Handle with care.'],
  ['heart', 'Someone’s loved one'],
  ['heart', 'Heart on a bike'],
  ['heart', 'Human, not a hazard'],
  ['eye', 'I see you. See me too.'],
  ['eye', 'Check your blind spot'],
  ['eye', 'Look before you open your door'],
  ['eye', 'Mirror. Signal. Wait.'],
  ['octagon', 'Stop rushing'],
  ['octagon', 'Pause. Then pass.'],
  ['octagon', 'Take a breath'],
  ['octagon', 'Worth the wait'],
  ['no-phone', 'Text later. I’d like to live.'],
  ['no-phone', 'Your message can wait'],
  ['no-phone', 'Phone down. Eyes up.'],
  ['no-horn', 'Honking won’t help'],
  ['no-horn', 'Quiet please. Cyclist concentrating.'],
  ['no-horn', 'Wave, don’t honk'],
]

export function sloganId(text: string) {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[’']/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

export function libraryFor(collection: Exclude<Collection, 'signs'>, lines: string[]) {
  return lines.map((text) => ({ id: sloganId(text), text, collection }))
}
